from __future__ import annotations

NAME = 'claudino'
DESCRIPTION = 'Layout Laboratorio Claudino, incluindo fallback para PDFs sem camada de texto.'
DEFAULTS = {'line_y_tolerance': 3.0}

FIELD_RULES = [{'description': 'Substituir nome do paciente na primeira pagina (fallback sem camada de texto)',
  'rect': [92.0, 37.0, 325.0, 54.0],
  'replacement': 'Paciente A',
  'fontname': 'hebo',
  'fontsize': 9.0,
  'min_fontsize': 5.0,
  'text_color': (0, 0, 0),
  'preserve_style': False,
  'pages': '1',
  'enabled': True,
  'requires_no_text': True},
 {'description': 'Remover medico solicitante no cabecalho (fallback sem camada de texto)',
  'rect': [91.0, 55.0, 335.0, 72.0],
  'replacement': '',
  'pages': '1',
  'enabled': True,
  'requires_no_text': True},
 {'description': 'Remover convenio no cabecalho (fallback sem camada de texto)',
  'rect': [499.0, 55.0, 563.0, 72.0],
  'replacement': '',
  'pages': '1',
  'enabled': True,
  'requires_no_text': True},
 {'description': 'Remover atendimento no cabecalho (fallback sem camada de texto)',
  'rect': [77.0, 76.0, 140.0, 92.0],
  'replacement': '',
  'pages': '1',
  'enabled': True,
  'requires_no_text': True},
 {'description': 'Remover atendente no cabecalho (fallback sem camada de texto)',
  'rect': [322.0, 76.0, 404.0, 92.0],
  'replacement': '',
  'pages': '1',
  'enabled': True,
  'requires_no_text': True},
 {'description': 'Remover impressao no cabecalho (fallback sem camada de texto)',
  'rect': [499.0, 76.0, 587.0, 92.0],
  'replacement': '',
  'pages': '1',
  'enabled': True,
  'requires_no_text': True}]

GRAPHIC_AREA_RULES = []

AREA_RULES = [{'description': 'Remove repeated header on continuation pages',
  'rect': [0, 0, None, 83],
  'fill': (1, 1, 1),
  'pages': '2-',
  'enabled': True},
 {'description': 'Remove footer block',
  'rect': [0, 690, None, None],
  'fill': (1, 1, 1),
  'pages': 'all',
  'enabled': True}]

TEXT_RULES = [{'description': "Replace patient name after 'Paciente:'",
  'pattern': '(?i)\\bPaciente:\\s*(?P<value>.+?)(?=\\s+(?:Idade/Sexo:|M[eé]dico\\b|Conv[eê]nio:)|$)',
  'group': 'value',
  'replacement': 'Paciente A',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'text_color': (0, 0, 0),
  'pad': 0.25,
  'pages': '1',
  'enabled': True},
 {'description': "Remove physician name after 'Médico Dr(a).'",
  'pattern': '(?i)\\bM[eé]dico\\s+Dr\\(a\\)\\.\\s*(?P<value>.*?)(?=\\s*(?:Conv[eê]nio:|Atendimento:|Idade/Sexo:|Local:|$))',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.25,
  'pages': '1',
  'enabled': True},
 {'description': "Remove health plan / insurance value after 'Convênio:'",
  'pattern': '(?i)\\bConv[eê]nio:\\s*(?P<value>.+?)(?=\\s+(?:Atendimento:|Idade/Sexo:|Local:)|$)',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.25,
  'pages': '1',
  'enabled': True},
 {'description': "Remove attendance ID after 'Atendimento:'",
  'pattern': '(?i)\\bAtendimento:\\s*(?P<value>\\S+)',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.0,
  'pages': '1',
  'enabled': True},
 {'description': "Remove attendant name after 'Atendente:'",
  'pattern': '(?i)\\bAtendente:\\s*(?P<value>.+?)(?=\\s+(?:Local:|Impress[aã]o:)|$)',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.0,
  'pages': '1',
  'enabled': True},
 {'description': "Remove print timestamp after 'Impressão:'",
  'pattern': '(?i)\\bImpress[aã]o:\\s*(?P<value>\\d{2}/\\d{2}/\\d{4}\\s+\\d{2}:\\d{2}(?::\\d{2})?)',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.0,
  'pages': '1',
  'enabled': True},
 {'description': 'OPTIONAL: remove date/time immediately after attendance ID',
  'pattern': '(?i)\\bAtendimento:\\s*\\S+\\s+(?P<value>\\d{2}/\\d{2}/\\d{4}\\s+\\d{2}:\\d{2}(?::\\d{2})?)',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontsize': 7,
  'fontname': 'helv',
  'pad': 0.2,
  'pages': '1',
  'enabled': False}]

STAMP_RULES = [{'description': 'Add laboratory identifier above first-page header',
  'text': 'Laboratório: Claudino',
  'rect': [27, 10, 576, 24],
  'fontname': 'helv',
  'fontsize': 14,
  'color': (0, 0, 0),
  'align': 'left',
  'pages': '1',
  'enabled': True}]


# Profile-specific hooks can be added here if generic CLI overrides are not enough.
def apply_overrides(profile, args):
    return None
