from __future__ import annotations

NAME = 'dbdiagnosticos'
DESCRIPTION = 'Layout DBDiagnosticos.'
DEFAULTS = {'line_y_tolerance': 3.0}

FIELD_RULES = [{'description': 'Substituir nome do paciente na primeira pagina',
  'rect': [64.0, 78.5, 185.0, 92.0],
  'replacement': 'Paciente A',
  'preserve_style': True,
  'fontname': 'helv',
  'fontsize': 8.0,
  'pages': '1',
  'enabled': True},
 {'description': 'Remover apoiado/posto de coleta no cabecalho',
  'rect': [59.0, 91.0, 256.0, 105.0],
  'replacement': '',
  'pages': '1',
  'enabled': True},
 {'description': 'Remover codigo do apoiado no cabecalho',
  'rect': [375.0, 89.5, 415.0, 100.0],
  'replacement': '',
  'pages': '1',
  'enabled': True},
 {'description': 'Remover numero do pedido no cabecalho',
  'rect': [510.0, 90.0, 556.0, 102.0],
  'replacement': '',
  'pages': '1',
  'enabled': True},
 {'description': 'Remover solicitante no cabecalho',
  'rect': [71.0, 104.0, 265.0, 117.0],
  'replacement': '',
  'pages': '1',
  'enabled': True},
 {'description': 'Remover cidade/UF no cabecalho',
  'rect': [71.0, 117.0, 141.0, 130.0],
  'replacement': '',
  'pages': '1',
  'enabled': True},
 {'description': 'Remover CPF no cabecalho',
  'rect': [375.0, 118.0, 428.0, 130.0],
  'replacement': '',
  'pages': '1',
  'enabled': True}]

GRAPHIC_AREA_RULES = [{'description': 'Remover QR code sem afetar texto',
  'rect': [0.0, 0.0, 120.0, 79.5],
  'pages': 'all',
  'fill': (1, 1, 1),
  'enabled': True},
 {'description': 'Remover codigo de barras sem afetar texto',
  'rect': [470.0, 78.0, 558.0, 112.0],
  'pages': 'all',
  'fill': (1, 1, 1),
  'enabled': True}]

AREA_RULES = [{'description': 'Remover cabecalho repetido nas paginas de continuacao',
  'rect': [0.0, 0.0, None, 131.0],
  'pages': '2-',
  'fill': (1, 1, 1),
  'enabled': True},
 {'description': 'Remover rodape visual inferior',
  'rect': [0.0, 660.0, None, None],
  'pages': 'all',
  'fill': (1, 1, 1),
  'enabled': True}]

TEXT_RULES = [{'description': 'Remover linha DB CONTAGEM CNES',
  'pattern': '(?i)^\\s*DB\\s+CONTAGEM\\s+CNES:\\s*\\S+\\s*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.0,
  'footer_signature': True,
  'enabled': False},
 {'description': 'Remover rotulo Assinatura digital',
  'pattern': '(?i)^\\s*Assinatura\\s+digital:\\s*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True},
 {'description': 'Remover hash de assinatura digital',
  'pattern': '^\\s*[A-F0-9]{40,}\\s*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True},
 {'description': 'Remover texto de amostra biologica',
  'pattern': '(?i)\\bAmostra\\s+biol[oó]gica\\s+coletada.*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True},
 {'description': 'Remover linha paciente/coletado em',
  'pattern': '(?i)^\\s*paciente\\.\\s+Coletado\\s+em\\s+.*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True},
 {'description': 'Remover Assinado eletronicamente em',
  'pattern': '(?i)\\bAssinado\\s+eletronicamente\\s+em:\\s*\\S.*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True},
 {'description': 'Remover medico assinante',
  'pattern': '(?i)^\\s*por\\s+Dr\\.?\\s+.+$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'footer_signature': True,
  'enabled': True}]

STAMP_RULES = []


# Profile-specific hooks can be added here if generic CLI overrides are not enough.
def apply_overrides(profile, args):
    return None
