from __future__ import annotations

NAME = 'hermes_pardini'
DESCRIPTION = 'Layout Hermes Pardini.'
DEFAULTS = {'line_y_tolerance': 3.0}

FIELD_RULES = []

GRAPHIC_AREA_RULES = []

AREA_RULES = [{'description': 'Replace patient name field',
  'rect': [51, 107, 410, 122],
  'replacement': 'Paciente A',
  'preserve_style': True,
  'fontname': 'cobo',
  'fontsize': 13.0,
  'min_fontsize': 6.0,
  'text_color': (0, 0, 0),
  'fill': (1, 1, 1),
  'align': 'left',
  'pages': '1',
  'enabled': True},
 {'description': 'Preserve birth date and age by default',
  'rect': [426, 107, 550, 121],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': False},
 {'description': 'Remove requester / physician field',
  'rect': [51, 136, 290, 151],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': True},
 {'description': 'Preserve entry date field by default',
  'rect': [405, 137, 468, 149.5],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': False},
 {'description': 'Remove lab order number field',
  'rect': [471, 137, 548, 149.5],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': True},
 {'description': 'Remove conveniado order number value',
  'rect': [500.5, 149.8, 531.0, 157.1],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': True},
 {'description': 'Remove address / regulatory text to the right of the logo',
  'rect': [250, 55, 456, 90],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '1',
  'enabled': True},
 {'description': 'Remove repeated header on continuation pages',
  'rect': [0, 0, None, 160],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': '2-',
  'enabled': True},
 {'description': 'Remove right-side vertical print timestamp',
  'rect': [561, 80, 574, 238],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': 'all',
  'enabled': True},
 {'description': 'Remove left-side vertical release / technician stamp',
  'rect': [42, 232, 61, 330],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': 'all',
  'enabled': True},
 {'description': 'Remove footer / signature block',
  'rect': [0, 735, None, None],
  'replacement': '',
  'fill': (1, 1, 1),
  'pages': 'all',
  'enabled': True}]

TEXT_RULES = [{'description': 'Remove collection date/time value',
  'pattern': '(?i)\\[DATA\\s+DA\\s+COLETA\\s*:\\s*(?P<value>\\d{2}/\\d{2}/\\d{4}\\s+\\d{2}:\\d{2})\\]',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontname': 'cour',
  'fontsize': 8,
  'fill': (1, 1, 1),
  'pad': 0.25,
  'pages': 'all',
  'enabled': True},
 {'description': 'Remove digital signature hash value',
  'pattern': '(?i)nro:\\s*(?P<value>[A-F0-9]{20,})',
  'group': 'value',
  'replacement': '',
  'preserve_style': True,
  'fontname': 'helv',
  'fontsize': 7,
  'fill': (1, 1, 1),
  'pad': 0.25,
  'pages': 'all',
  'enabled': True}]

STAMP_RULES = [{'description': 'Optional laboratory identifier stamp',
  'text': 'Laboratório: Hermes Pardini',
  'rect': [43, 18, 560, 32],
  'fontname': 'helv',
  'fontsize': 10,
  'color': (0, 0, 0),
  'align': 'left',
  'pages': '1',
  'enabled': False}]


# Profile-specific hooks can be added here if generic CLI overrides are not enough.
def apply_overrides(profile, args):
    return None
