from __future__ import annotations

NAME = 'ipc'
DESCRIPTION = 'Layout do laboratorio IPC.'
DEFAULTS = {'line_y_tolerance': 3.0}

FIELD_RULES = [{'description': 'Limpar faixa de campos do cabecalho na primeira pagina',
  'rect': [27.0, 88.0, 568.0, 145.0],
  'replacement': '',
  'pages': '1',
  'enabled': True}]

GRAPHIC_AREA_RULES = []

AREA_RULES = [{'description': 'Remover contatos e selo do topo direito na primeira pagina',
  'rect': [280.0, 8.0, None, 90.0],
  'pages': '1',
  'fill': (1, 1, 1),
  'enabled': True},
 {'description': 'Remover CNPJ do topo direito na primeira pagina',
  'rect': [170.0, 60.0, None, 90.0],
  'pages': '1',
  'fill': (1, 1, 1),
  'enabled': True},
 {'description': 'Remover cabecalho completo em paginas de continuacao',
  'rect': [0.0, 0.0, None, 150.0],
  'fill': (1, 1, 1),
  'pages': '2-',
  'enabled': True},
 {'description': 'Remover rodape com assinatura/aviso',
  'rect': [0.0, 680.0, None, None],
  'fill': (1, 1, 1),
  'pages': 'all',
  'enabled': True}]

TEXT_RULES = [{'description': 'Remover linha Conferido por',
  'pattern': '(?i)^\\s*Conferido\\s+por:\\s*.+$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'enabled': True},
 {'description': 'Remover linha de assinatura digital, se nao coberta pelo rodape',
  'pattern': '(?i)^\\s*Este\\s+laudo\\s+foi\\s+assinado\\s+digitalmente\\s+sob\\s+o\\s+n[ºo]:\\s*[A-F0-9]{20,}\\s*$',
  'replacement': '',
  'pages': 'all',
  'pad': 0.6,
  'enabled': True}]

STAMP_RULES = [{'description': 'label Paciente',
  'text': 'Paciente:',
  'rect': [34.5, 91.0, 70.0, 102.5],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'valor Paciente',
  'text': 'Paciente A',
  'rect': [74.0, 89.0, 220.0, 103.2],
  'fontname': 'DejaVuSans-Bold',
  'fontsize': 8.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'bold'},
 {'description': 'label Data de Nascimento',
  'text': 'Data de Nascimento:',
  'rect': [33.8, 104.0, 110.0, 115.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'valor Data de Nascimento',
  'text': '11/05/1967',
  'rect': [132.0, 104.0, 195.0, 115.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Solicitante',
  'text': 'Solicitante Dr(a).',
  'rect': [34.5, 117.5, 100.0, 128.8],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Convenio',
  'text': 'Convênio:',
  'rect': [34.5, 132.0, 72.0, 143.0],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Atendimento',
  'text': 'Atendimento:',
  'rect': [308.2, 93.0, 357.0, 104.0],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Data',
  'text': 'Data:',
  'rect': [308.2, 107.4, 329.5, 118.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'valor Data',
  'text': '24/04/2026',
  'rect': [333.0, 107.4, 395.0, 118.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Impressao',
  'text': 'Impressão:',
  'rect': [307.5, 124.0, 349.0, 134.7],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Numero',
  'text': 'Número:',
  'rect': [462.7, 93.0, 495.0, 104.0],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Horario',
  'text': 'Horario:',
  'rect': [462.7, 107.4, 493.0, 118.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'valor Horario',
  'text': '09:28',
  'rect': [503.2, 107.4, 530.0, 118.2],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'},
 {'description': 'label Atendente',
  'text': 'Atendente:',
  'rect': [462.0, 124.0, 503.0, 134.7],
  'fontname': 'DejaVuSans',
  'fontsize': 7.5,
  'pages': '1',
  'enabled': True,
  'fontfile_role': 'regular'}]


# Profile-specific hooks can be added here if generic CLI overrides are not enough.
def apply_overrides(profile, args):
    return None
